[package]
name = "libradicl-macros"
version = "0.13.0"
authors.workspace = true
edition.workspace = true
description = "Procedural macros for libradicl"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/libradicl-macros"
include = ["src/*.rs", "/Cargo.toml"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = { version = "2.0.117", features = ["full"] }
